###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Belay Zeleke
# Your name to show in the footer
author: Belay Zeleke
###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Abounavbar-links:
  ABOUT ME: "aboutme"
  RESUME: "resume"
  PROJECTS: "projects"
  EDUCATION: "education"
  RESEARCH: "research"
  BLOG: "blog"
